#' @title Select the Extra Parameter for a Multivariate BCS-NSM Regression Fit
#'
#' @description
#' Estimates the extra parameter in a multivariate BCS-NSM regression fit 
#' by profiling the log-likelihood over a grid of values in the interval (0, 1).
#'
#' @param object an object of class \code{"bcsnsm"}, a result of a call to \code{\link{bcsnsm}}.
#' @param copula character; informs which normal scale mixture distribution
#'     should be used to generate the NSM copula. The copulas with extra parameters are 
#'     the \eqn{t} copula (\code{copula = "t"}), slash copula (\code{copula = "slash"}),
#'     and hyperbolic copula (\code{copula = "hyp"}).
#' @param grid numeric vector with values in (0, 1); the grid of \code{eta} values used to 
#'     evaluate the profiled log-likelihood. If the tweaks are not computationally intensive, 
#'     we suggest \code{grid = seq(0.5, 0.98, 0.04)}.
#' @param trace logical; if \code{TRUE}, a summary with the profiled log-likelihood value, the AIC,
#'     and the BIC of the fit is displayed.
#' @param plot logical; if \code{TRUE}, a graph of the profiled log-likelihood evaluated in the
#'     considered grid of values is shown.
#' @param control a list of control arguments specified via \code{\link[bcsnsm]{control_fit}}.
#' @param ... further arguments passed to \code{\link[bcsnsm]{control_fit}}.
#'
#'
#' @return An object of class \code{"choose_copula"}, which is a named list where
#'     which each element is a \code{"\link{bcsnsm}"} fitted with a different value of the extra 
#'     parameter specified in \code{grid}.
#'
#'     The \code{print} method summarizes the fits by displaying, for each value in \code{grid},
#'     the log-likelihood value and the Akaike (AIC) and Bayesian (BIC) information criteria. The
#'     \code{plot} method returns a graph of the profiled likelihood of the extra parameter, 
#'     .highlighting the value that maximizes the profiled log-likelihood.
#'     
#' @details
#' The extra parameter is denoted by \code{eta}, which is reparameterized to take values 
#' in the interval (0, 1) for numerical stability. For instance, if
#' \code{delta} is a positive extra parameter induced by the normal scale mixture copula,
#' we consider the reparameterization \code{eta = delta / (1 + delta)}. Thus, for example,
#' under the \emph{t} copula, \code{eta} corresponds to \code{eta / (1 - eta)} degrees of freedom.
#' This function evaluates the profiled log-likelihood over a grid of \code{eta} values and returns 
#' the fitted models for each one. The optimal value can be selected based on the log-likelihood, AIC, or BIC.
#'
#' @references Ferrari, S. L. P., and Fumes, G. (2017). Box-Cox symmetric distributions and applications to
#'     nutritional data. \emph{AStA Advances in Statistical Analysis}, \bold{101}, 321--344.
#'
#'     Medeiros, R. M. R. de, and Ferrari, S. L. P. (2025). Multivariate Box-Cox symmetric distributions
#'         generated by a normal scale mixture copula.
#'     
#'     Vanegas, L. H., and Paula, G. A. (2016). Log-symmetric distributions: statistical properties and
#'     parameter estimation. \emph{Brazilian Journal of Probability and Statistics}, \bold{30}, 196--220.
#'
#' @author Rodrigo M. R. de Medeiros <\email{rodrigo.matheus@ufrn.br}>
#'
#' @examples
#' # Data set: macronutrients (for description run ?macronutrients)
#' # Consider modeling the animal and plant protein regarding income level
#' 
#' ## Response distribution:
#' mvplot(macronutrients[, 1:2])
#' 
#' ## Animal and plant protein by income level:
#' boxplot(animal_p ~ income, macronutrients)
#' boxplot(plant_p ~ income, macronutrients)
#' 
#' ## Reference model
#' fit0 <- bcsnsm(animal_p + plant_p ~ income | income, data = macronutrients)
#' fit0
#' 
#' ## Fitting a t copula
#' fit_t <- choose_copula(fit0, copula = "t")
#' 
#' # Class
#' class(fit_t)
#' 
#' # It is possible to recover the plot:
#' plot(fit_t)
#' 
#' # And the model selection summary:
#' fit_t
#' 
#' # Fit with eta = 0.9
#' fit_t[["0.9"]]
#' summary(fit_t[["0.9"]])
#' @export
choose_copula <- function(object, grid = seq(0.5, 0.98, 0.04), copula, trace = TRUE, plot = TRUE,
                          control = control_fit(...), ...) {
  
  if (trace) 
    cat(crayon::cyan("BCS-NSM multivariate regression with", copula, "copula\n"))
  
  n <- object$nobs
  fit_update <- lapply(grid, function(eta) {
    
    init <- Sys.time()
    opt <- try(stats::update(object, copula = copula, eta = eta, control = control), silent = TRUE)
    end <- Sys.time()
    
    if (trace) {
      cat(
        "\neta:", eta,
        "|",
        "logLik:", if (unique(grepl("Error", opt))) NA else sprintf("%.3f", stats::logLik(opt)),
        "|",
        "AIC:", if (unique(grepl("Error", opt))) NA else sprintf("%.3f", stats::AIC(opt)),
        "|",
        "BIC:", if (unique(grepl("Error", opt))) NA else sprintf("%.3f", stats::AIC(opt, k = log(n))),
        "|",
        "Time to run:", sprintf("%.3f", difftime(end, init, units = "mins"))
      )
    }
    
    opt
  })
  
  if (plot) {
    
    ll <- vector("numeric", length = length(grid))
    for (i in 1:length(grid)) {
      ll[i] <- if (unique(grepl("Error", fit_update[i]))) NA else stats::logLik(fit_update[[i]])
    }
    
    plot(grid, ll, type = "o", pch = 16, cex = 0.6,
         xlab = expression(eta), ylab = "Profiled log-likelihood")
    graphics::abline(v = grid[which.max(ll)], lty = 3, col = "grey", lwd = 2)
    graphics::points(c(grid[which.max(ll)], grid[which.max(ll)]), c(ll[which.max(ll)], ll[which.max(ll)]),
                     col = c("#56B1F7", 1), pch = c(16, 1))
    
    
  }
  
  if (trace) {
    cat(crayon::cyan("\n\nBest value for eta according profiled logLik:"), grid[which.max(ll)])  
  }
  
  
  fit_update <- stats::setNames(fit_update, grid)
  class(fit_update) <- "choose_copula"
  fit_update
}


# Print
#' @rdname choose_copula
#' @param x an object of class \code{"choose_copula"}.
#' @param ... further arguments passed to or from other methods.
#' @export
print.choose_copula <- function(x, ...) {

  cat(crayon::cyan("BCS-NSM multivariate regression with", x[[1]]$copula, "copula\n"))

  grid <- names(x)
  i <- 1
  ll <- AIC <- BIC <- vector("numeric", length(grid))
  for (eta in grid) {
    ll[i] <- if (unique(grepl("Error", x[[i]]))) NA else round(as.numeric(stats::logLik(x[[i]])), 3)
    AIC[i] <- if (unique(grepl("Error", x[[i]]))) NA else round(stats::AIC(x[[i]]), 3)
    BIC[i] <- if (unique(grepl("Error", x[[i]]))) NA else round(stats::AIC(x[[i]], k = log(x[[i]]$nobs)), 3)

    cat(
      "eta:", eta,
      "|",
      "logLik:", sprintf("%.3f", ll[i]),
      "|",
      "AIC:", sprintf("%.3f", AIC[i]),
      "|",
      "BIC:", sprintf("%.3f", BIC[i]), "\n"
    )

    i <- i + 1
  }

  cat(crayon::cyan("\nBest value for eta according to AIC:"), grid[which.min(AIC)], crayon::cyan("BIC:"), grid[which.min(BIC)],
      crayon::cyan("and logLik:"), grid[which.max(ll)])

  invisible(x)
}


# Plot
#' @rdname choose_copula
#' @export
plot.choose_copula <- function(x, ...) {
  grid <- names(x)

  ll <- vector()
  for (i in 1:length(grid)) {
    ll[i] <- if (unique(grepl("Error", x[[i]]))) NA else stats::logLik(x[[i]])
  }

  plot(grid, ll, type = "o", pch = 16, cex = 0.6,
       xlab = expression(eta), ylab = "Profile log-likelihood")
  graphics::abline(v = grid[which.max(ll)], lty = 3, col = "grey", lwd = 2)
  graphics::points(c(grid[which.max(ll)], grid[which.max(ll)]), c(ll[which.max(ll)], ll[which.max(ll)]),
                   col = c("#56B1F7", 1), pch = c(16, 1))

  invisible(x)
}
