# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hyp_PDF <- function(x, mu, sigma, nu, log_p = FALSE) {
    .Call('_bcsnsm_hyp_PDF', PACKAGE = 'bcsnsm', x, mu, sigma, nu, log_p)
}

